name: use awpec to perform 
inputs:
  working-directory:
      description: set working directory; default is .
      required: false
      default: '.'
  tfvar-env:
    description: tfvars workspace parameters to use
    required: true

runs:
  using: "composite"
  steps:
    - name: setup runner
      uses: ThoughtWorks-DPS/lab-runner-setup-action@main
      with:
        install-awspec: "true"
    - name: run awspec tests
      env:
        TEST_ENV: ${{ inputs. tfvars-env }}
      run: bash scripts/cluster_configuration_tests.sh ${{ inputs. tfvars-env }}

