on:
  push:
    branches:
      - "main"
    tags:
      - "!*"

jobs:
  validate-terraform:
    name: validate terraform
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: setup pipeline runner and environment variables
        uses: ./.github/actions/setup-pipeline-env
        with:
          secrethub-creds: ${{ secrets.SECRETHUB_CREDENTIAL }}
          tfvar-env: gha-sandbox
      - name: run tflint, terraform validate, and terraform fmt checks
        uses: ThoughtWorks-DPS/terraform-action@main
        env:
          TF_WORKSPACE: gha-sandbox
        with:
          terraform-cloud-token: $TERRAFORM_CLOUD_TOKEN
          lint: true
          fmt-check-terraform: true
          validate-terraform: true

  gha-sandbox-change-plan:
    name: gha-sandbox plan changes
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: setup pipeline runner and environment
        uses: ./.github/actions/setup-pipeline-env
        with:
          secrethub-creds: ${{ secrets.SECRETHUB_CREDENTIAL }}
          tfvar-env: gha-sandbox
      - name: terraform plan for gha-sandbox environment
        uses: ThoughtWorks-DPS/terraform-action@main
        env:
          TF_WORKSPACE: gha-sandbox
        with:
          terraform-cloud-token: $TERRAFORM_CLOUD_TOKEN
          plan: true

  # github repository configuration has gha-sandbox environment defined
  # and requires team member approval to perform this job
  gha-sandbox-apply-changes:
    name: gha-sandbox apply changes
    needs: [ validate-terraform, gha-sandbox-change-plan ]
    runs-on: ubuntu-latest
    environment:
      name: gha-sandbox
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: hello
        run: echo "will run tf apply here"
      - name: setup pipeline runner and environment
        uses: ./.github/actions/setup-pipeline-env
        with:
          secrethub-creds: ${{ secrets.SECRETHUB_CREDENTIAL }}
          tfvar-env: gha-sandbox
      - name: terraform apply for gha-sandbox environment
        uses: ThoughtWorks-DPS/terraform-action@main
        env:
          TF_WORKSPACE: gha-sandbox
        with:
          terraform-cloud-token: $TERRAFORM_CLOUD_TOKEN
          apply: true

  gha-sandbox-test-eks-changes:
    name: gha-sandbox test changes
    needs: gha-sandbox-apply-changes
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: setup pipeline runner and environment
        uses: ./.github/actions/setup-pipeline-env
        with:
          secrethub-creds: ${{ secrets.SECRETHUB_CREDENTIAL }}
          tfvar-env: gha-sandbox
      - name: validate eks cluster
        uses: ./.github/actions/test-eks
        with:
          tfvar-env: gha-sandbox
