name: changes merged to main

on:
  push:
    branches:
      - "main"
    tags:
      - "!*"

jobs:

  validate-terraform:
    name: validate terraform
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: configure shared pipeline job environment
        uses: ./.github/actions/shared-pipeline-env
        with:
          secrethub-creds: ${{ secrets.SECRETHUB_CREDENTIAL }}
          tfvar-env: gha-sandbox
      - name: run tflint, terraform validate, and terraform fmt checks
        uses: ThoughtWorks-DPS/terraform-action@main
        env:
          TF_WORKSPACE: gha-sandbox
        with:
          terraform-cloud-token: $TERRAFORM_CLOUD_TOKEN
          lint: true
          fmt-check-terraform: true
          validate-terraform: true

  gha-sandbox-change-plan:
    name: gha-sandbox plan changes
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: configure shared pipeline job environment
        uses: ./.github/actions/shared-pipeline-env
        with:
          secrethub-creds: ${{ secrets.SECRETHUB_CREDENTIAL }}
          tfvar-env: gha-sandbox
      - name: terraform plan for gha-sandbox environment
        uses: ThoughtWorks-DPS/terraform-action@main
        env:
          TF_WORKSPACE: gha-sandbox
        with:
          terraform-cloud-token: $TERRAFORM_CLOUD_TOKEN
          plan: true

  # github repository configuration has gha-sandbox environment defined
  # and requires team member approval to perform this job
  gha-sandbox-apply-changes:
    name: gha-sandbox apply changes
    needs: [ validate-terraform, gha-sandbox-change-plan ]
    runs-on: ubuntu-latest
    environment:
      name: gha-sandbox
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: configure shared pipeline job environment
        uses: ./.github/actions/shared-pipeline-env
        with:
          secrethub-creds: ${{ secrets.SECRETHUB_CREDENTIAL }}
          tfvar-env: gha-sandbox
      - name: setup runner
        uses: ThoughtWorks-DPS/lab-runner-setup-action@main
        with:
          install-awspec: "true"
      - name: terraform apply for gha-sandbox environment
        uses: ThoughtWorks-DPS/terraform-action@main
        env:
          TF_WORKSPACE: gha-sandbox
          TEST_ENV: gha-sandbox
        with:
          terraform-cloud-token: $TERRAFORM_CLOUD_TOKEN
          awspec-test: true
          test-assume-role: true
          apply: true
